-- BURGERSHOT ITENS	
["burgerlife"] = {
		["name"] = "burgerlife",
		["label"] = "burgerlife",
		["weight"] = 0,
		["type"] = "item",
		["image"] = "burgerlife.png",
		["unique"] = false,
		["useable"] = true,
		["shouldClose"] = true,
		["combinable"] = nil,
		["description"] = "Menu BurgerLife - BurgerShot Produto"
  },
  ["menuburger"] = {
	["name"] = "menuburger",
	["label"] = "menuburger",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menuburger.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Menu BurgerLife - BurgerShot Produto"
},
["menugift1"] = {
	["name"] = "menugift1",
	["label"] = "menugift1",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menugift1.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Presente do Menu - BurgerShot Produto"
},
["menugift2"] = {
	["name"] = "menugift2",
	["label"] = "menugift2",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menugift2.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Presente do Menu - BurgerShot Produto"
},
["menugift3"] = {
	["name"] = "menugift3",
	["label"] = "menugift3",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menugift3.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Presente do Menu - BurgerShot Produto"
},
["menubatatas"] = {
	["name"] = "menubatatas",
	["label"] = "menubatatas",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menubatatas.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Batatas Fritas - BurgerShot Produto"
},
["menubebida"] = {
	["name"] = "menubebida",
	["label"] = "menubebida",
	["weight"] = 0,
	["type"] = "item",
	["image"] = "menubebida.png",
	["unique"] = false,
	["useable"] = true,
	["shouldClose"] = true,
	["combinable"] = nil,
	["description"] = "Bebida Fresca - BurgerShot Produto"
},
